language: c
compiler: gcc

before_script:
        - git clone https://github.com/sisoputnfrba/so-commons-library.git
	- cd so-commons-library

install: sudo make install

before_script:
	- cd kemmens/Debug

script: make all

branches:
  only: master
